# homebrewのパッケージをインストールするための設定
##################################################
# homebrew のアップグレードは個別にやる
#   brew upgrade [PACKAGE名]

# homebrewのクリーン
#   brew cleanup

# homebrew-caskのクリーン
#  brew cask cleanup
##################################################

- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no

  vars:
    homebrew_taps:
      - caskroom/cask
      - caskroom/versions

      - yusabana/custom
      - sanemat/font                    # Font Ricty http://morizyun.github.io/blog/ricty-font-homebrew-mac/
      - peco/peco
      - homebrew/dupes
      - homebrew/versions
      - homebrew/boneyard
      - homebrew/apache
      - homebrew/php
      - homebrew/binary
    homebrew_packages:
      - { name: awscli }        # http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
      - { name: ansible }
      - { name: automake }
      - { name: ccat }
      - { name: cmake }
      - { name: colordiff }
      - { name: ctags }
      - { name: direnv }
      - { name: git }
      - { name: go }
      - { name: hub }
      - { name: httpd22 }
      # - { name: httpd24 } #httpd22と共存できない
      - { name: imagemagick }
#      - { name: icu4c, state: linked }   # 明示的にリンクを貼る brew link --force icu4c ## 一時的に何に使っているかわからないのでコメントアウトしておく
      - { name: jq }
      - { name: jmeter }
      - { name: lha }
      - { name: libmcrypt }              # phpenv, php-build で必要
      - { name: mercurial }
      - { name: mpg123 }
      - { name: mysql }
      - { name: nginx }
      - { name: nkf }
      - { name: openssl }
      - { name: packer }
      - { name: peco }
      - { name: phantomjs }
#      - { name: php55 }
#      - { name: php55-mcrypt }           #laravelに必要
      - { name: plantuml }
      - { name: postgresql }
      - { name: pow }
      - { name: pstree }
      - { name: pkg-config }
      - { name: python }
      - { name: re2c }  # php-build に必要
      - { name: reattach-to-user-namespace } # 自分でビルドする方法もあり .tmux.conf参照
      - { name: readline }
      - { name: redis }
# なぜかインストールできない      - { name: ricty }
      - { name: rsense }
      - { name: subversion }
      - { name: the_platinum_searcher }
      - { name: the_silver_searcher }
      - { name: tig }
      - { name: tika }
      - { name: tmux-patched }
      - { name: tree }
      - { name: w3m }
      - { name: watch }
      - { name: wget }
      - { name: whois }
      - { name: z }
      - { name: zsh }

    homebrew_cask_packages:
      - { name: alfred }
      - { name: atom }
      - { name: android-file-transfer }
      - { name: bartender }
      - { name: charles }
      - { name: calibre }
      - { name: clipmenu }
      - { name: cyberduck }
      - { name: evernote }
      - { name: dropbox }
      # - { name: flashlight } #spotlightを便利にするツール alfredを使うため一旦除外
      - { name: firefox-ja }
      - { name: gyazo }
      - { name: google-japanese-ime }
      - { name: google-chrome }
      - { name: heroku-toolbelt }
      - { name: hipchat }
      - { name: iterm2 }
      - { name: java }
      - { name: keepassx }
      - { name: karabiner }
      - { name: macdown }
      - { name: macvim-kaoriya }
      - { name: magican }
      - { name: mysqlworkbench }
      - { name: opera }
      - { name: processing }
      - { name: prott }
      - { name: rubymine }
      - { name: skitch }
      - { name: skype }
      - { name: slack }
      - { name: sourcetree }
      - { name: spark }
      - { name: visual-studio-code }
      - { name: virtualbox }
      - { name: vagrant }
      - { name: xquartz }

  tasks:
    ## homebrew 関連 ##
    - name: homebrew update
      homebrew: update_homebrew=yes
    - name: homebrew tap
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps
    - name: homebrew packages install
      homebrew: name={{ item.name }} state={{ item.state|default("present") }}
      with_items: homebrew_packages
    #- name: homebrew installed packages upgrade
    #- homebrew: update_homebrew=yes upgrade_all=yes


    ## homebrew cask 関連 ##
    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"  # homebrew-caskでよくあること http://qiita.com/tienlen/items/1a50c7507c8f6454f6c6
      with_items: homebrew_cask_packages

