[[plugins]]
# neocomplcacheのsinpet補完
repo = 'Shougo/neosnippet'
on_i = 1

[[plugins]]
# refs. http://d.hatena.ne.jp/osyo-manga/20140112/1389525543
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
# vimスニペット集 https://github.com/honza/vim-snippets/tree/master/snippets
repo = 'honza/vim-snippets.git'
on_i = 1

[[plugins]]
# if...endやdef...endなどを書きだしてくれる
repo = 'tpope/vim-endwise'
on_i = 1

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'perl-support.vim'
on_ft = ['perl']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'skwp/vim-rspec'
on_ft = ['ruby']

[[plugins]]
# slimテンプレートのシンタックス
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']
depends = ['open-browser.vim']
