#!/usr/bin/env perl

use strict;
use warnings;

=head1 DESCRIPTION
一括renameスクリプト mvコマンドを表示するだけ。対象外のやつもとりあえず表示している。
使い方(aaa を bbb に変える) mv-all aaa bbb |sh
=cut

my ($before, $after) = @ARGV;
system 'for f in `ls`; do echo "mv $f ${f/'.$before.'/'.$after.'}"; done';


