#!/bin/bash
# https://qiita.com/shima_6_you/items/cae79e54171143c14ba3
# 引数でカラーコードを渡す
# $ tmuxchcolor # これで変更する
# $ tmuxchcolor default # これで元に戻す
# color=${1:-colour8}
bgcolor=${1:-colour240}

if [[ -n $(printenv TMUX) ]] ; then
    # pane_id=$(tmux display -p '#{pane_id}')
    tmux select-pane -P "bg=${bgcolor}"
else
    echo 'Not use tmux'
fi
