# homebrewのパッケージをインストールするための設定
##################################################
# homebrew のアップグレードは個別にやる
#   brew upgrade [PACKAGE名]

# homebrewのクリーン
#   brew cleanup

# homebrew-caskのクリーン
#  brew cask cleanup
##################################################

- hosts: localhost
  connection: local
  gather_facts: false
  become: false

  vars:
    homebrew_taps:
      - homebrew/cask
      - homebrew/cask-versions
      - argon/mas
      - tkengo/highway

    homebrew_cask_packages:
      - name: virtualbox  # インストール前に security の設定で Oracle を allowする必要がある
      - name: alfred
      - name: appcleaner
      # - name: android-studio
      - name: bartender
      - name: blisk
      # - name: boostnote
      - name: homebrew/cask-fonts/font-fira-code
      - name: charles
      - name: calibre
      - name: contexts
      - name: cyberduck
      - name: discord
      - name: docker   # docker for mac
      - name: drawio
      - name: dropbox
      # - name: dbeaver-community # DBクライアント
      - name: firefox
      - name: google-japanese-ime
      - name: google-chrome
      # - name: hyper
      - name: iterm2
      - name: intellij-idea
      - name: java
      - name: kap
      - name: karabiner-elements
      - name: keepassx
      - name: kindle
      - name: kindlegen
      - name: krisp
      - name: licecap
      - name: marp
      - name: mysqlworkbench  # DB(mysql)クライアント
      - name: ngrok           # [ngrokを使用してローカル環境を外部に公開する - Qiita](https://qiita.com/kitaro729/items/44214f9f81d3ebda58bd)
      - name: noun-project
      - name: onedrive
      - name: postman
      - name: shiftit
      - name: skitch
      # - name: skype
      - name: slack
      - name: tableplus # DBクライアント
      - name: vagrant
      - name: visual-studio-code
      - name: vivaldi
      - name: xmind
      - name: xquartz
      - name: zoomus

    homebrew_packages:
      - name: asciinema
      - name: awscli        # http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
      - name: automake
      - name: ccat
      - name: certbot
      - name: cmake
      - name: csshx
      - name: colordiff
      - name: ctags
      - name: direnv
      - name: ffmpeg
      - name: fzf
      - name: git
      - name: gnuplot # gnuplot コマンドで特定のデータからコマンドで簡単にグラフ化するツール
      - name: highlight
      - name: highway
      - name: hub
      - name: imagemagick   # imagemagickはrmagickの関係でver6系を入れる。後に対応されたらver7以上とする
      - name: jq
      - name: jmeter
      - name: lesspipe
      - name: lha
      - name: lua
      - name: mas
      - name: mecab
      - name: mecab-ipadic
      - name: mongodb
      - name: mosquitto
      - name: mpg123
      - name: mycli
      - name: mysql-client
      - name: neovim
      - name: nginx
      - name: ngrep
      - name: nkf
      - name: openssl
      - name: pandoc  # http://sky-y.github.io/site-pandoc-jp/users-guide/
      - name: packer
      - name: peco
      - name: plantuml
      - name: pgcli
      - name: pstree
      - name: pkg-config
#      - name: python
#      - name: python3
      - name: reattach-to-user-namespace  # 自分でビルドする方法もあり .tmux.conf参照
      - name: readline
      - name: subversion
      - name: terraform
      - name: the_platinum_searcher
      - name: the_silver_searcher
      - name: tidy-html5 # tidyのlintでhtml5として有効となるように
      - name: tig
      - name: tmux
      - name: tree
      - name: unar   # zipなどの解凍ツール(winのcp932などでも文字化けしないように)
      - name: v8-315 # therubyracerに必要
      - name: vim
      - name: w3m
      - name: watch
      - name: wget
      - name: whois
      - name: yarn
      - name: youtube-dl
      - name: zsh

  tasks:
    - name: homebrew install
      shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      args:
        creates: /usr/local/bin/brew

    ## homebrew cask 関連 ##
    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      environment:
        # homebrew-caskでよくあること http://qiita.com/tienlen/items/1a50c7507c8f6454f6c6
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"  
      with_items: '{{ homebrew_cask_packages }}'

    ## homebrew 関連 ##
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

    # - name: homebrew installed packages upgrade
    # - homebrew: update_homebrew=yes upgrade_all=yes
