# homebrewのパッケージをインストールするための設定
##################################################
# homebrew のアップグレードは個別にやる
#   brew upgrade [PACKAGE名]

# homebrewのクリーン
#   brew cleanup

# homebrew-caskのクリーン
#  brew cask cleanup
##################################################

- hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
    - name: already exist homebrew ?
      shell: which brew
      register: exist_brew
      failed_when: no
    - name: homebrew install
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      when: exist_brew.rc != 0

    ## homebrew 関連 ##
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    # - name: homebrew installed packages upgrade
    # - homebrew: update_homebrew=yes upgrade_all=yes
