- hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
    #- name: Add homebrew's zsh binary in /etc/shells
    #  lineinfile:
    #    path: /etc/shells
    #    state: present
    #    line: /usr/local/bin/zsh
    #  become: true

    #- name: Enable homebrew's zsh
    #  shell: chsh -s /usr/local/bin/zsh
    #  become: true
    #  changed_when: false

    - name: Install zinit
      shell: sh -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
      args:
        creates: ~/.zinit

    - name: Backup original zshrc of oh-my-zsh
      shell: mv ~/.zshrc ~/.zshrc_bk_zinit
      args:
        creates: ~/.zshrc_bk_zinit
