- hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
    - name: Add homebrew's zsh binary in /etc/shells
      lineinfile:
        path: /etc/shells
        state: present
        line: /usr/local/bin/zsh
      become: true

    - name: Enable homebrew's zsh
      shell: chsh -s /usr/local/bin/zsh
      become: true
      changed_when: false

    - name: Install zplugin
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
      args:
        creates: ~/.zplugin

    - name: Backup original zshrc of oh-my-zsh
      shell: mv ~/.zshrc ~/.zshrc_bk_zplugin
      args:
        creates: ~/.zshrc_bk_zplugin
