- hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
    - name: Install vim-plug for vim8
      shell: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      args:
        creates: ~/.vim/autoload/plug.vim
    - name: Install vim-plug for neovim
      shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      args:
        creates: ~/.local/share/nvim/site/autoload/plug.vim
