# homebrewのパッケージをインストールするための設定
##################################################
# homebrew のアップグレードは個別にやる
#   brew upgrade [PACKAGE名]

# homebrewのクリーン
#   brew cleanup

# homebrew-caskのクリーン
#  brew cask cleanup
##################################################

- hosts: localhost
  connection: local
  gather_facts: false
  become: false

  vars:
    homebrew_taps:
      - caskroom/cask
      - caskroom/versions
      - homebrew/dupes
      - homebrew/versions
      - homebrew/boneyard
      - homebrew/binary
      - argon/mas
      - tkengo/highway

    homebrew_cask_packages:
      - name: alfred
      - name: appcleaner
      # - name: virtualbox
      - name: atom
      - name: bartender
      - name: blisk
      - name: charles
      - name: calibre
      - name: contexts
      - name: cyberduck
      - name: dbeaver-community
      - name: docker   # docker for mac
      - name: dropbox
      - name: firefox
      - name: gyazo
      - name: google-japanese-ime
      - name: google-chrome
      - name: iterm2
      - name: java
      - name: karabiner-elements
      - name: keepassx
      - name: kindle
      - name: kindlegen
      - name: licecap
      - name: mysqlworkbench
      - name: onedrive
      - name: postman
      - name: skitch
      - name: skype
      - name: slack
      - name: vagrant
      - name: visual-studio-code
      - name: xmind
      - name: xquartz

    homebrew_packages:
      - name: awscli        # http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
      # - name: ansible # pipでインストール
      - name: automake
      - name: ccat
      - name: certbot
      - name: chromedriver
      - name: cmake
      - name: colordiff
      - name: ctags
      - name: direnv
      - name: fzf
      - name: git
      # - name: go
      - name: highlight
      - name: highway
      - name: hub
      - name: imagemagick@6   # imagemagickはrmagickの関係でver6系を入れる。後に対応されたらver7以上とする
      - name: jq
      - name: jmeter
      - name: lesspipe
      - name: lha
      - name: lua
      - name: mas
      # - name: mercurial
      - name: mosquitto
      - name: mpg123
      - name: mycli
      - name: mysql
      - name: neovim
      - name: nginx
      - name: ngrep
      - name: nkf
      - name: openssl
      - name: packer
      - name: plantuml
      - name: pgcli
      - name: pstree
      - name: pkg-config
      # - name: python
      # - name: python3
      - name: reattach-to-user-namespace  # 自分でビルドする方法もあり .tmux.conf参照
      - name: readline
      - name: subversion
      - name: terraform
      - name: the_platinum_searcher
      - name: the_silver_searcher
      - name: tidy-html5 # tidyのlintでhtml5として有効となるように
      - name: tig
      - name: tmux
      - name: tree
      - name: w3m
      - name: watch
      - name: wget
      - name: whois
      - name: yarn
      - name: zsh
    homebrew_packages_with_options:
      - name: curl
        options: 'with-openssl,with-nghttp2'
      - name: vim
        options: 'with-lua,with-python3'

  tasks:
    ## homebrew cask 関連 ##
    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"  # homebrew-caskでよくあること http://qiita.com/tienlen/items/1a50c7507c8f6454f6c6
      with_items: '{{ homebrew_cask_packages }}'

    ## homebrew 関連 ##
    - name: homebrew update
      homebrew:
        update_homebrew: yes
    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'
    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'
    - name: homebrew packages install with options
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
        install_options: '{{ item.options }}'
      with_items: '{{ homebrew_packages_with_options }}'
    # - name: homebrew installed packages upgrade
    # - homebrew: update_homebrew=yes upgrade_all=yes
