[settings]
experimental = true
# lockfile = true
pipx.uvx = true

[tools]
node = "22"
python = "3.12"
# ruby = "3.3"
ripgrep = "latest"
uv = "latest"
gh = "latest"
"npm:@openai/codex" = "latest"

[tasks.apps]
description = "Brewfile に基づいて GUI アプリをインストール/更新"
run = """
brew bundle check --file=./Brewfile && brew bundle --file=./Brewfile --no-upgrade
"""

[tasks.setup]
description = "開発環境をまとめて用意（ツール＋アプリ）"
depends = ["apps"]
run = "mise install"  # tools 節のツールをインストール

[tasks.zsh]
description = "zshのセットアップ"
run = """
bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
"""

[tasks.symlinks]
description = "dotfiles からホームディレクトリへのシンボリックリンクを作成"
run = "bash ~/.config/mise/scripts/apply-symlinks.sh"
